AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Include:
    - "lib/generators/mkdocs_rails/install/templates/bin/docs.tt"

Lint/ScriptPermission:
  Exclude:
    - "lib/generators/mkdocs_rails/install/templates/bin/docs.tt"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
